---
title: "托幼机构文献阅读总结"
author:
  - 曾同志
documentclass: ctexart
geometry: "left=2.5cm,right=2cm,top=3cm,bottom=2.5cm"
keywords:
  - 托幼机构文献
  - 空气污染
bibliography: nursery.bib
csl: "china-national-standard-gb-t-7714-2015-numeric.csl"
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
---

# 重要词汇

1. IAQ：Indoor air pollution，室内空气质量；
2. 


# What do we know about indoor air quality of nurseries? A review of the literature

article1[@zhangWhatWeKnow]

## 基本信息

1. 文章类型：review article
2. 年代：2021年
3. 影响因子：Q3 2.47

## 研究目的

针对托幼机构(nursery)的室内空气污染研究很匮乏，但除了在家里，学生大部分时间都花在了学校，危害包括哮喘、呼吸系统疾病等。因此，本研究回顾总结了针对托幼机构室内空气污染的研究，来提供证据更好地了解托幼机构室内空气质量现况。

## 研究结论

1. 托幼机构空气污染往往超过推荐值(guidlines)。
2. 设计人员和政策制定人员应认识到托幼机构室内空气污染对学生的影响。

## 背景

1. 人们在室内的时间占到了90%。src2
2. 监测室内空气污染面临的挑战：
  - 建筑物特征（通风、泄露、建筑年龄）；
  - 居住者的特征；
  - 室外污染物。
3. 室内污染要比室外污染对健康的影响大。
4. 6岁以下儿童暴露在环境污染物中受到的危害比成人大：
  - 儿童的免疫系统和呼吸系统还没有发育完全；
  - 儿童有更大的表面积体积比；
  - 儿童的呼吸速率更快；
  - 儿童待在室内的时间更长，工作日在教室内平均7-11h/d；src3
  - 研究提示室内空气污染对儿童的中枢神经系统有潜在影响；src4
  - 一岁前暴露在空气污染中可加重哮喘的发展；src5（2015）
5. 之前的研究都主要集中在办公室和住宅楼，针对学校的研究也多集中在小学(primary schools)和中学(secondary schools)，针对托幼机构的研究较少。
  

**参考文献**















